image: java:8-jdk

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: ./gradlew --build-cache assemble -s
  artifacts:
    paths:
      - subprojects/**/build/libs/*.jar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: 
    - ./gradlew check jacocoTestReport codeCoverageReport
    - grep -Eo "Total.*?([0–9]{1,3})%" build/reports/jacoco/codeCoverageReport/html/index.html
    - bash <(curl -s https://codecov.io/bash)
  artifacts:
    reports:
      junit: subprojects/**/build/test-results/**/TEST-*.xml
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
 
test with JDK 11:
  image: openjdk:11-jdk
  stage: test
  script: ./gradlew check
  artifacts:
    reports:
      junit: subprojects/**/build/test-results/**/TEST-*.xml
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
      
test with JDK 13:
  image: openjdk:13-jdk
  stage: test
  script: ./gradlew check
  allow_failure: true
  artifacts:
    reports:
      junit: subprojects/**/build/test-results/**/TEST-*.xml
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
